version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"                 # Expose Apache on port 80
    volumes:
      - ./stufeems:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: stufeedb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d  # Mount db_init for SQL initialization
    ports:
      - "3306:3306"

volumes:
  db_data:
